<?php
/*
 * Copyright (c) 2013 The Olympos Development Team.
 * 
 * http://sourceforge.net/projects/olympos/
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html. If redistributing this code,
 * this entire header must remain intact.
 */

/**
 * This file was generated by ChronosGenerator  from cwm-export.uml on Tue Feb 19 19:45:32 CET 2013. 
 * Manual modifications should be placed inside the protected regions.
 */
namespace testapp\application\model;

use wcmf\lib\model\Node;

use wcmf\lib\i18n\Message;
use wcmf\lib\persistence\ObjectId;

/**
 * @class NMPageDocument
 * NMPageDocument description: ?
 *
 * @author 
 * @version 1.0
 */
class NMPageDocumentBase extends Node {

    /**
     * Constructor
     * @param oid ObjectId instance (optional)
     */
    public function __construct($oid=null) {
      if ($oid == null) {
        $oid = new ObjectId('NMPageDocument');
    }
      parent::__construct($oid);
    }

    /**
     * @see PersistentObject::getObjectDisplayName()
     */
    public function getObjectDisplayName() {
      return Message::get("NMPageDocument");
    }

    /**
     * @see PersistentObject::getObjectDescription()
     */
    public function getObjectDescription() {
      return Message::get("?");
    }

    /**
     * @see PersistentObject::getValueDisplayName()
     */
    public function getValueDisplayName($name) {
      $displayName = $name;
      if ($name == 'id') { $displayName = Message::get("id"); }
      if ($name == 'fk_page_id') { $displayName = Message::get("fk_page_id"); }
      if ($name == 'fk_document_id') { $displayName = Message::get("fk_document_id"); }
      return Message::get($displayName);
    }

    /**
     * @see PersistentObject::getValueDescription()
     */
    public function getValueDescription($name) {
      $description = $name;
      if ($name == 'id') { $description = Message::get(""); }
      if ($name == 'fk_page_id') { $description = Message::get(""); }
      if ($name == 'fk_document_id') { $description = Message::get(""); }
      return Message::get($description);
    }

    /**
     * Get the value of the id attribute
     * @param unconverted Boolean wether to get the converted or stored value (default: false)
     * @return Mixed
     */
    public function getId($unconverted=false) {
      $value = null;
      if ($unconverted) { $value = $this->getUnconvertedValue('id'); }
      else { $value = $this->getValue('id'); }
      return $value;
    }

    /**
     * Set the value of the id attribute
     * @param id The value to set
     */
    public function setId($id) {
      return $this->setValue('id', $id);
    }
    /**
     * Get the value of the fk_page_id attribute
     * @param unconverted Boolean wether to get the converted or stored value (default: false)
     * @return Mixed
     */
    public function getFkPageId($unconverted=false) {
      $value = null;
      if ($unconverted) { $value = $this->getUnconvertedValue('fk_page_id'); }
      else { $value = $this->getValue('fk_page_id'); }
      return $value;
    }

    /**
     * Set the value of the fk_page_id attribute
     * @param fk_page_id The value to set
     */
    public function setFkPageId($fk_page_id) {
      return $this->setValue('fk_page_id', $fk_page_id);
    }
    /**
     * Get the value of the fk_document_id attribute
     * @param unconverted Boolean wether to get the converted or stored value (default: false)
     * @return Mixed
     */
    public function getFkDocumentId($unconverted=false) {
      $value = null;
      if ($unconverted) { $value = $this->getUnconvertedValue('fk_document_id'); }
      else { $value = $this->getValue('fk_document_id'); }
      return $value;
    }

    /**
     * Set the value of the fk_document_id attribute
     * @param fk_document_id The value to set
     */
    public function setFkDocumentId($fk_document_id) {
      return $this->setValue('fk_document_id', $fk_document_id);
    }
     
    /**
     * Get the Document instances in the Document relation
     * @return Array of Document instances
     */
    public function getDocumentList() {
      return $this->getParentsEx(null, 'Document');
        }

    /**
     * Set the Document instances in the Document relation
     * @param nodeList Array of Document instances
     */
    public function setDocumentList(array $nodeList) {
      $this->setValue('Document', null);
      foreach ($nodeList as $node) {
        $this->addNode($node, 'Document');
      }
      }
    /**
     * Get the Page instances in the Page relation
     * @return Array of Page instances
     */
    public function getPageList() {
      return $this->getParentsEx(null, 'Page');
        }

    /**
     * Set the Page instances in the Page relation
     * @param nodeList Array of Page instances
     */
    public function setPageList(array $nodeList) {
      $this->setValue('Page', null);
      foreach ($nodeList as $node) {
        $this->addNode($node, 'Page');
      }
      }
}
?>
