<?php
/*
 * Copyright (c) 2013 The Olympos Development Team.
 * 
 * http://sourceforge.net/projects/olympos/
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html. If redistributing this code,
 * this entire header must remain intact.
 */

/**
 * This file was generated by ChronosGenerator  from cwm-export.uml on Sun Apr 28 21:58:27 CEST 2013. 
 * Manual modifications should be placed inside the protected regions.
 */
namespace testapp\application\model;

use testapp\application\model\NMPublisherAuthorBase;
// PROTECTED REGION ID(testapp/application/model/NMPublisherAuthor.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class NMPublisherAuthor
 * NMPublisherAuthor description: ?
 *
 * @author 
 * @version 1.0
 */
class NMPublisherAuthor extends NMPublisherAuthorBase {
// PROTECTED REGION ID(testapp/application/model/NMPublisherAuthor.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
