#
# This file was generated by ChronosGenerator  from model.uml.
# Manual modifications should be placed inside the protected regions.
#
#
# Structure of Table `DBSequence`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `DBSequence`;
CREATE TABLE `DBSequence` # entityType=DBSequence tableId=_s2Ve4LTMEeOYkOsR5IzpsA
(
  `id` INT(11) NOT NULL, # columnId=_b3EKUM73EeOwXYBK5uMsvQ 
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
#
# Structure of Table `Locktable`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Locktable`;
CREATE TABLE `Locktable` # entityType=Locktable tableId=_s73fILTMEeOYkOsR5IzpsA
(
  `id` INT(11) NOT NULL, # columnId=_b2-Dtc73EeOwXYBK5uMsvQ 
  `fk_user_id` INT(11), # columnId=_b2-DsM73EeOwXYBK5uMsvQ referencedTable=User
  `objectid` VARCHAR(255), # columnId=_EVGnsLTTEeOYkOsR5IzpsA 
  `sessionid` VARCHAR(255), # columnId=_EXZGsLTTEeOYkOsR5IzpsA 
  `since` DATETIME, # columnId=_EZrlsLTTEeOYkOsR5IzpsA 
  PRIMARY KEY (`id`)
  ,KEY `fk_user_id` (`fk_user_id`)
) ENGINE=MyISAM;
#
# Structure of Table `Language`
# A language for which a translation of the model can be created. The code is arbitrary but it is recommended to use the ISO language codes (en, de, it, ...).
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Language`;
CREATE TABLE `Language` # entityType=Language tableId=_s5AYYLTMEeOYkOsR5IzpsA
(
  `id` INT(11) NOT NULL, # columnId=_b2rv0M73EeOwXYBK5uMsvQ 
  `name` VARCHAR(255), # columnId=_mThnQLTOEeOYkOsR5IzpsA 
  `code` VARCHAR(255), # columnId=_mWMgwLTOEeOYkOsR5IzpsA 
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
#
# Structure of Table `Translation`
# Instances of this class are used to localize entity attributes. Each instance defines a translation of one attribute of one entity into one language.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Translation`;
CREATE TABLE `Translation` # entityType=Translation tableId=_tCKUYLTMEeOYkOsR5IzpsA
(
  `id` INT(11) NOT NULL, # columnId=_b2fikM73EeOwXYBK5uMsvQ 
  `objectid` VARCHAR(255), # columnId=_4sa_QLTQEeOYkOsR5IzpsA 
  `attribute` VARCHAR(255), # columnId=_4vqggLTQEeOYkOsR5IzpsA 
  `translation` TEXT, # columnId=_4zGPALTQEeOYkOsR5IzpsA 
  `language` VARCHAR(255), # columnId=_42VwQLTQEeOYkOsR5IzpsA 
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
#
# Structure of Table `User`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `User`;
CREATE TABLE `User` # entityType=User tableId=_tJBxYLTMEeOYkOsR5IzpsA
(
  `id` INT(11) NOT NULL, # columnId=_b3ck0M73EeOwXYBK5uMsvQ 
  `login` VARCHAR(255), # columnId=_P0GFcLTREeOYkOsR5IzpsA 
  `password` VARCHAR(255), # columnId=_P23FkLTREeOYkOsR5IzpsA 
  `name` VARCHAR(255), # columnId=_P5h_ELTREeOYkOsR5IzpsA 
  `firstname` VARCHAR(255), # columnId=_P8fMcLTREeOYkOsR5IzpsA 
  `config` VARCHAR(255), # columnId=_P_cZ0LTREeOYkOsR5IzpsA 
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
#
# Structure of Table `UserConfig`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `UserConfig`;
CREATE TABLE `UserConfig` # entityType=UserConfig tableId=_tFTvALTMEeOYkOsR5IzpsA
(
  `id` INT(11) NOT NULL, # columnId=_b2TVVc73EeOwXYBK5uMsvQ 
  `fk_user_id` INT(11), # columnId=_b2TVUM73EeOwXYBK5uMsvQ referencedTable=User
  `key` VARCHAR(255), # columnId=_1-0UELTREeOYkOsR5IzpsA 
  `val` VARCHAR(255), # columnId=_2AoR8LTREeOYkOsR5IzpsA 
  PRIMARY KEY (`id`)
  ,KEY `fk_user_id` (`fk_user_id`)
) ENGINE=MyISAM;
#
# Structure of Table `Role`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Role`;
CREATE TABLE `Role` # entityType=Role tableId=_s_A5wLTMEeOYkOsR5IzpsA
(
  `id` INT(11) NOT NULL, # columnId=_b3QXkM73EeOwXYBK5uMsvQ 
  `name` VARCHAR(255), # columnId=_blxxgLTWEeOYkOsR5IzpsA 
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
#
# Structure of Table `NMUserRole`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `NMUserRole`;
CREATE TABLE `NMUserRole` # entityType=NMUserRole tableId=_tM8BALTMEeOYkOsR5IzpsA
(
  `fk_role_id` INT(11), # columnId=_b2HIFM73EeOwXYBK5uMsvQ referencedTable=Role
  `fk_user_id` INT(11), # columnId=_b2BBcM73EeOwXYBK5uMsvQ referencedTable=User
  PRIMARY KEY (`fk_role_id`,`fk_user_id`)
) ENGINE=MyISAM;
#
# Structure of Table `Publisher`
# A publisher publishes books.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Publisher`;
CREATE TABLE `Publisher` # entityType=Publisher tableId=_BDrKMLU2EeORdpT3S9OOtw
(
  `id` INT(11) NOT NULL, # columnId=_b100MM73EeOwXYBK5uMsvQ 
  `name` VARCHAR(255), # columnId=_UsqjALU2EeORdpT3S9OOtw 
  `created` DATETIME, # columnId=_b1jucM73EeOwXYBK5uMsvQ 
  `creator` VARCHAR(255), # columnId=_b1mxxM73EeOwXYBK5uMsvQ 
  `modified` DATETIME, # columnId=_b1pOAM73EeOwXYBK5uMsvQ 
  `last_editor` VARCHAR(255), # columnId=_b1sRVM73EeOwXYBK5uMsvQ 
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
#
# Structure of Table `Author`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Author`;
CREATE TABLE `Author` # entityType=Author tableId=_BGWqwLU2EeORdpT3S9OOtw
(
  `id` INT(11) NOT NULL, # columnId=_b1eO4M73EeOwXYBK5uMsvQ 
  `name` VARCHAR(255), # columnId=_rq2WALU2EeORdpT3S9OOtw 
  `created` DATETIME, # columnId=_b1I3sM73EeOwXYBK5uMsvQ 
  `creator` VARCHAR(255), # columnId=_b1NJJM73EeOwXYBK5uMsvQ 
  `modified` DATETIME, # columnId=_b1QMdM73EeOwXYBK5uMsvQ 
  `last_editor` VARCHAR(255), # columnId=_b1Ud4873EeOwXYBK5uMsvQ 
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
#
# Structure of Table `Book`
# A book is published by a publisher and consists of chapters.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Book`;
CREATE TABLE `Book` # entityType=Book tableId=_BJe3QLU2EeORdpT3S9OOtw
(
  `id` INT(11) NOT NULL, # columnId=_b1DYI873EeOwXYBK5uMsvQ 
  `fk_publisher_id` INT(11), # columnId=_b1CxEM73EeOwXYBK5uMsvQ referencedTable=Publisher
  `title` VARCHAR(255), # columnId=__mzRoLU3EeORdpT3S9OOtw 
  `description` VARCHAR(255), # columnId=__p_vkLU3EeORdpT3S9OOtw 
  `year` VARCHAR(255), # columnId=__svhkLU3EeORdpT3S9OOtw 
  `created` DATETIME, # columnId=_b0fXcM73EeOwXYBK5uMsvQ 
  `creator` VARCHAR(255), # columnId=_b0msNM73EeOwXYBK5uMsvQ 
  `modified` DATETIME, # columnId=_b0qWkc73EeOwXYBK5uMsvQ 
  `last_editor` VARCHAR(255), # columnId=_b0v2JM73EeOwXYBK5uMsvQ 
  PRIMARY KEY (`id`)
  ,KEY `fk_publisher_id` (`fk_publisher_id`)
) ENGINE=MyISAM;
#
# Structure of Table `Chapter`
# A book is divided into chapters. A chapter may contain subchapters.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Chapter`;
CREATE TABLE `Chapter` # entityType=Chapter tableId=_BMnDwLU2EeORdpT3S9OOtw
(
  `id` INT(11) NOT NULL, # columnId=_b0ZQ0M73EeOwXYBK5uMsvQ 
  `fk_chapter_id` INT(11), # columnId=_b0YpwM73EeOwXYBK5uMsvQ referencedTable=Chapter
  `fk_book_id` INT(11), # columnId=_b0YCsM73EeOwXYBK5uMsvQ referencedTable=Book
  `fk_author_id` INT(11), # columnId=_b0W0kM73EeOwXYBK5uMsvQ referencedTable=Author
  `name` VARCHAR(255), # columnId=_kq-u8LU4EeORdpT3S9OOtw 
  `created` DATETIME, # columnId=_bznNsM73EeOwXYBK5uMsvQ 
  `creator` VARCHAR(255), # columnId=_bztUVc73EeOwXYBK5uMsvQ 
  `modified` DATETIME, # columnId=_bzza9c73EeOwXYBK5uMsvQ 
  `last_editor` VARCHAR(255), # columnId=_bz5hlc73EeOwXYBK5uMsvQ 
  `sortkey_author` INT(11), # columnId=sortkey_author
  `sortkey_book` INT(11), # columnId=sortkey_book
  `sortkey_parentchapter` INT(11), # columnId=sortkey_parentchapter
  `sortkey` INT(11), # columnId=sortkey
  PRIMARY KEY (`id`)
  ,KEY `fk_chapter_id` (`fk_chapter_id`)
  ,KEY `fk_book_id` (`fk_book_id`)
  ,KEY `fk_author_id` (`fk_author_id`)
) ENGINE=MyISAM;
#
# Structure of Table `Image`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Image`;
CREATE TABLE `Image` # entityType=Image tableId=_BQLVILU2EeORdpT3S9OOtw
(
  `id` INT(11) NOT NULL, # columnId=_bzhHGs73EeOwXYBK5uMsvQ 
  `fk_chapter_id` INT(11), # columnId=_bzhHFc73EeOwXYBK5uMsvQ referencedTable=Chapter
  `fk_titlechapter_id` INT(11), # columnId=_bzhHEM73EeOwXYBK5uMsvQ referencedTable=Chapter
  `file` VARCHAR(255), # columnId=_0UxuULU4EeORdpT3S9OOtw 
  `created` DATETIME, # columnId=_by2YsM73EeOwXYBK5uMsvQ 
  `creator` VARCHAR(255), # columnId=_by8fVc73EeOwXYBK5uMsvQ 
  `modified` DATETIME, # columnId=_bzCl9c73EeOwXYBK5uMsvQ 
  `last_editor` VARCHAR(255), # columnId=_bzIslc73EeOwXYBK5uMsvQ 
  `sortkey_titlechapter` INT(11), # columnId=sortkey_titlechapter
  `sortkey_normalchapter` INT(11), # columnId=sortkey_normalchapter
  `sortkey` INT(11), # columnId=sortkey
  PRIMARY KEY (`id`)
  ,KEY `fk_chapter_id` (`fk_chapter_id`)
  ,KEY `fk_titlechapter_id` (`fk_titlechapter_id`)
) ENGINE=MyISAM;
#
# Structure of Table `NMPublisherAuthor`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `NMPublisherAuthor`;
CREATE TABLE `NMPublisherAuthor` # entityType=NMPublisherAuthor tableId=_BTThoLU2EeORdpT3S9OOtw
(
  `id` INT(11) NOT NULL, # columnId=_byd-Oc73EeOwXYBK5uMsvQ 
  `fk_author_id` INT(11), # columnId=_byd-NM73EeOwXYBK5uMsvQ referencedTable=Author
  `fk_publisher_id` INT(11), # columnId=_byX3kM73EeOwXYBK5uMsvQ referencedTable=Publisher
  `sortkey_publisher` INT(11), # columnId=sortkey_publisher
  `sortkey_author` INT(11), # columnId=sortkey_author
  `sortkey` INT(11), # columnId=sortkey
  PRIMARY KEY (`id`)
  ,KEY `fk_author_id` (`fk_author_id`)
  ,KEY `fk_publisher_id` (`fk_publisher_id`)
) ENGINE=MyISAM;
