#
# This file was generated by wCMFGenerator 3.0.0017 from newroles.uml on Thu Apr 28 13:05:07 CEST 2011. 
# Manual modifications should be placed inside the protected regions.
#
#
# Structure of Table `adodbseq`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `adodbseq`;
CREATE TABLE `adodbseq` # entityType=Adodbseq tableId={3C3FC8F0-DD8A-4ad9-BB10-403825A48C9C}
(
  `id` INT(11) NOT NULL, # columnId=_Xq2xgHGHEeCC75F7wFLlkw 
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
#
# Structure of Table `language`
# A llanguage for which a translation of the model can be created. The code is arbitrary but it is recommended to use the ISO language codes (en, de, it, ...).
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `language`;
CREATE TABLE `language` # entityType=Language tableId={279AE4E5-852E-4b71-A8B4-C1E5E220D600}
(
  `id` INT(11) NOT NULL, # columnId=_XqQ7oHGHEeCC75F7wFLlkw 
  `code` VARCHAR(255), # columnId={B6B7AE1F-487C-4180-8A26-6F4E1549FB3B} 
  `name` VARCHAR(50), # columnId={256E0BF8-0BE7-4c47-86C5-596B1F2E1D09} 
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
#
# Structure of Table `locktable`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `locktable`;
CREATE TABLE `locktable` # entityType=Locktable tableId={ADC6F227-2E89-41a1-8EA3-9B73820EC9D8}
(
  `id` INT(11) NOT NULL, # columnId=_Xp9ZpHGHEeCC75F7wFLlkw 
  `fk_user_id` INT(11), # columnId=_Xp0PsHGHEeCC75F7wFLlkw referencedTable=UserRDB
  `objectid` VARCHAR(255), # columnId={C18AF095-575E-4c60-9240-37EE7976CEB5} 
  `sessionid` VARCHAR(255), # columnId={C690480B-E434-4675-807B-7DA3C1FC71E9} 
  `since` VARCHAR(255), # columnId={436EB7C1-122C-42c2-81F2-D519B950E934} 
  PRIMARY KEY (`id`)
  ,KEY `fk_user_id` (`fk_user_id`)
) ENGINE=MyISAM;
#
# Structure of Table `nm_user_role`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `nm_user_role`;
CREATE TABLE `nm_user_role` # entityType=NMUserRole tableId={4AB7C88E-CE09-4fba-A8C9-1DBEEC9B5EFC}
(
  `fk_user_id` INT(11), # columnId=_XpXjwHGHEeCC75F7wFLlkw referencedTable=UserRDB
  `fk_role_id` INT(11), # columnId=_XpNywHGHEeCC75F7wFLlkw referencedTable=RoleRDB
  PRIMARY KEY (`fk_user_id`,`fk_role_id`)
) ENGINE=MyISAM;
#
# Structure of Table `role`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` # entityType=RoleRDB tableId={74CB3FF5-27C7-435e-BECA-F3511F6A181D}
(
  `id` INT(11) NOT NULL, # columnId=_XrmYYHGHEeCC75F7wFLlkw 
  `name` VARCHAR(50), # columnId={451E3B0C-4DF2-4f43-9F9E-88306EFE8D68} 
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
#
# Structure of Table `translation`
# Instances of this class are used to localize entity attributes. Each instance defines a translation of one attribute of one entity into one language.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `translation`;
CREATE TABLE `translation` # entityType=Translation tableId={09F69DF1-0E20-4135-855A-3179FD436B8F}
(
  `id` INT(11) NOT NULL, # columnId=_XoeL4HGHEeCC75F7wFLlkw 
  `objectid` VARCHAR(255), # columnId={822CEADC-526A-4347-A050-1F4F74148D88} 
  `attribute` VARCHAR(255), # columnId={65FC01D8-85D4-47c8-B2B1-CE0445408A3A} 
  `translation` TEXT, # columnId={C91D5D0C-5188-4bcb-8B44-53FA82ECE470} 
  `language` VARCHAR(255), # columnId={710A1A8E-F609-4cb3-95DE-76FA5A8D0A25} 
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
#
# Structure of Table `user_config`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `user_config`;
CREATE TABLE `user_config` # entityType=UserConfig tableId={64185B6F-3928-4aae-9DDF-825A7EAE46D6}
(
  `id` INT(11) NOT NULL, # columnId=_XoBf8HGHEeCC75F7wFLlkw 
  `fk_user_id` INT(11), # columnId=_Xn4WAHGHEeCC75F7wFLlkw referencedTable=UserRDB
  `key` VARCHAR(255), # columnId={98B69422-91BA-4358-8C1C-C2E2FF14FCB1} 
  `val` VARCHAR(255), # columnId={B724E946-0703-4036-86FA-AE784D10398D} 
  PRIMARY KEY (`id`)
  ,KEY `fk_user_id` (`fk_user_id`)
) ENGINE=MyISAM;
#
# Structure of Table `user`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` # entityType=UserRDB tableId={B8AEA9E2-2228-42b9-9121-FDA1DF50E05D}
(
  `id` INT(11) NOT NULL, # columnId=_XrTdcHGHEeCC75F7wFLlkw 
  `login` VARCHAR(50), # columnId={6FFE27BD-3B95-4828-B26A-A41AEC65B651} 
  `password` VARCHAR(255), # columnId={0F69EA9D-4963-4608-99DB-F35CE1159BDB} 
  `name` VARCHAR(50), # columnId={23BEDAEE-0278-4fb6-ABD1-E12AEE461A12} 
  `firstname` VARCHAR(50), # columnId={7AA15204-4902-45a5-AF96-599B511B4812} 
  `config` VARCHAR(255), # columnId={F0758E3B-E9D4-4dd9-A108-472A2CBE8CDA} 
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
