#
# This file was generated by wCMFGenerator 2.6.1.0033 from cookbook1.xmi on 23.02.09 21:34. 
# Manual modifications should be placed inside the protected regions.
#

#
# Structure of Table `locktable`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `locktable`;
CREATE TABLE `locktable` # entityType=Locktable tableId=EAID_ADC6F227_2E89_41a1_8EA3_9B73820EC9D8
(
  `id` INT(11) NOT NULL, # columnId=EAID_ADC6F227_2E89_41a1_8EA3_9B73820EC9D8_id 
  `fk_user_id` INT(11), # columnId=EAID_B8AEA9E2_2228_42b9_9121_FDA1DF50E05D_fk_user_id referencedTable=UserRDB
  `oid` VARCHAR(255), # columnId={C18AF095-575E-4c60-9240-37EE7976CEB5} 
  `sid` VARCHAR(255), # columnId={C690480B-E434-4675-807B-7DA3C1FC71E9} 
  `since` DATETIME, # columnId={436EB7C1-122C-42c2-81F2-D519B950E934} 
  PRIMARY KEY (`id`)
  ,KEY `fk_user_id` (`fk_user_id`)
) TYPE=MyISAM;
#
# Structure of Table `user`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` # entityType=UserRDB tableId=EAID_B8AEA9E2_2228_42b9_9121_FDA1DF50E05D
(
  `id` INT(11) NOT NULL, # columnId=EAID_B8AEA9E2_2228_42b9_9121_FDA1DF50E05D_id 
  `login` VARCHAR(50), # columnId={6FFE27BD-3B95-4828-B26A-A41AEC65B651} 
  `password` VARCHAR(50), # columnId={0F69EA9D-4963-4608-99DB-F35CE1159BDB} 
  `name` VARCHAR(50), # columnId={23BEDAEE-0278-4fb6-ABD1-E12AEE461A12} 
  `firstname` VARCHAR(50), # columnId={7AA15204-4902-45a5-AF96-599B511B4812} 
  `config` VARCHAR(255), # columnId={F0758E3B-E9D4-4dd9-A108-472A2CBE8CDA} 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `adodbseq`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `adodbseq`;
CREATE TABLE `adodbseq` # entityType=Adodbseq tableId=EAID_3C3FC8F0_DD8A_4ad9_BB10_403825A48C9C
(
  `id` INT(11) NOT NULL, # columnId=EAID_3C3FC8F0_DD8A_4ad9_BB10_403825A48C9C_id 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `nm_user_role`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `nm_user_role`;
CREATE TABLE `nm_user_role` # entityType=NMUserRole tableId=EAID_4AB7C88E_CE09_4fba_A8C9_1DBEEC9B5EFC
(
  `fk_user_id` INT(11), # columnId=EAID_B8AEA9E2_2228_42b9_9121_FDA1DF50E05D_fk_user_id referencedTable=UserRDB
  `fk_role_id` INT(11), # columnId=EAID_74CB3FF5_27C7_435e_BECA_F3511F6A181D_fk_role_id referencedTable=RoleRDB
  PRIMARY KEY (`fk_user_id`, `fk_role_id`)
  ,KEY `fk_user_id` (`fk_user_id`)
  ,KEY `fk_role_id` (`fk_role_id`)
) TYPE=MyISAM;
#
# Structure of Table `role`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` # entityType=RoleRDB tableId=EAID_74CB3FF5_27C7_435e_BECA_F3511F6A181D
(
  `id` INT(11) NOT NULL, # columnId=EAID_74CB3FF5_27C7_435e_BECA_F3511F6A181D_id 
  `name` VARCHAR(50), # columnId={451E3B0C-4DF2-4f43-9F9E-88306EFE8D68} 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `EntityBase`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `EntityBase`;
CREATE TABLE `EntityBase` # entityType=EntityBase tableId=EAID_D917962B_6527_43da_A5EF_0B42D7B11F0A
(
  `id` INT(11) NOT NULL, # columnId=EAID_D917962B_6527_43da_A5EF_0B42D7B11F0A_id 
  `created` DATETIME, # columnId={A53164C0-879C-4efa-86D2-A9379CDDA3A7} 
  `creator` VARCHAR(255), # columnId={8A6EED90-BB22-4b2d-9115-C61B6F25C110} 
  `modified` DATETIME, # columnId={C4065A47-D5C2-44dc-89DC-E52317788483} 
  `last_editor` VARCHAR(255), # columnId={7CC572DA-4CCC-4dfe-8F36-A665FFFA231C} 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
