<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from newroles.uml on Fri Jun 10 17:44:16 CEST 2011.
 * Manual modifications should be placed inside the protected regions.
 */
namespace application\model\wcmf;

use application\model\wcmf\NMUserRoleBase;
// PROTECTED REGION ID(application/include/model/wcmf/NMUserRole.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class NMUserRole
 * NMUserRole description:
 *
 * @author
 * @version 1.0
 */
class NMUserRole extends NMUserRoleBase
{
// PROTECTED REGION ID(application/include/model/wcmf/NMUserRole.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
