<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from newroles.uml on Tue May 17 15:35:25 CEST 2011. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(WCMF_BASE."application/include/model/wcmf/class.NMUserRoleBase.php");
// PROTECTED REGION ID(application/include/model/wcmf/class.NMUserRole.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class NMUserRole
 * NMUserRole description: 
 *
 * @author 
 * @version 1.0
 */
class NMUserRole extends NMUserRoleBase
{
// PROTECTED REGION ID(application/include/model/wcmf/class.NMUserRole.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
