<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from newroles.uml on Tue May 17 15:35:25 CEST 2011. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(WCMF_BASE."wcmf/lib/model/mapper/class.NodeUnifiedRDBMapper.php");
require_once(WCMF_BASE."application/include/model/wcmf/class.Locktable.php");

/**
 * @class LocktableRDBMapper
 * LocktableRDBMapper maps Locktable Nodes to the database.
 * Locktable description: 
 *
 * @author 
 * @version 1.0
 */
class LocktableRDBMapper extends NodeUnifiedRDBMapper
{
  /**
   * @see RDBMapper::getType()
   */
  public function getType()
  {
    return 'Locktable';
  }
  /**
   * @see PersistenceMapper::getPkNames()
   */
  public function getPkNames()
  {
    return array('id');
  }
  /**
   * @see PersistenceMapper::getProperties()
   */
  public function getProperties()
  {
    return array(
      'is_searchable' => false,
// PROTECTED REGION ID(application/include/model/wcmf/class.LocktableRDBMapper.php/Properties) ENABLED START
// PROTECTED REGION END
    );
  }
  /**
   * @see PersistenceMapper::isSortable()
   */
  public function isSortable()
  {
    return false;
  }
  /**
   * @see RDBMapper::getOwnDefaultOrder()
   */
  public function getOwnDefaultOrder($roleName=null)
  {
    return null;
  }
  /**
   * @see RDBMapper::getRelationDescriptions()
   */
  protected function getRelationDescriptions()
  {
    return array(
      'UserRDB' => new RDBManyToOneRelationDescription('Locktable', 'Locktable', 'UserRDB', 'UserRDB', '0', 'unbounded', '1', '1', 'none', 'composite', 'true', 'true', 'parent', 'id', 'fk_user_id'),
    
    );
  }
  /**
   * @see RDBMapper::getAttributeDescriptions()
   */
  protected function getAttributeDescriptions()
  {
    return array(
     /**
      * Value description: 
      */
      'id' => new RDBAttributeDescription('id', '', array('DATATYPE_IGNORE'), null, '', '', '', false, 'text', 'text', 'locktable', 'id'),
     /**
      * Value description: 
      */
      'fk_user_id' => new RDBAttributeDescription('fk_user_id', '', array('DATATYPE_IGNORE'), null, '', '', '', false, 'text', 'text', 'locktable', 'fk_user_id'),
     /**
      * Value description: 
      */
      'objectid' => new RDBAttributeDescription('objectid', 'string', array('DATATYPE_ATTRIBUTE'), null, '', '', '', false, 'text', 'text', 'locktable', 'objectid'),
     /**
      * Value description: 
      */
      'sessionid' => new RDBAttributeDescription('sessionid', 'string', array('DATATYPE_ATTRIBUTE'), null, '', '', '', false, 'text', 'text', 'locktable', 'sessionid'),
     /**
      * Value description: 
      */
      'since' => new RDBAttributeDescription('since', 'string', array('DATATYPE_ATTRIBUTE'), null, '', '', '', false, 'text', 'text', 'locktable', 'since'),
    );
  }
  /**
   * @see RDBMapper::createObject()
   */
  protected function createObject(ObjectId $oid=null)
  {
    return new Locktable($oid);
  }
  /**
   * @see NodeUnifiedRDBMapper::getTableName()
   */
  protected function getTableName()
  {
    return 'locktable';
  }
}
?>
