<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from newroles.uml on Tue Aug 24 08:05:29 CEST 2010. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/wcmf/class.LocktableBase.php");
// PROTECTED REGION ID(application/include/model/wcmf/class.Locktable.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class Locktable
 * Locktable description: 
 *
 * @author 
 * @version 1.0
 */
class Locktable extends LocktableBase
{
// PROTECTED REGION ID(application/include/model/wcmf/class.Locktable.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
