<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from newroles.uml on Tue May 17 15:35:25 CEST 2011.
 * Manual modifications should be placed inside the protected regions.
 */
require_once(WCMF_BASE."wcmf/lib/model/class.Node.php");

/**
 * @class NMUserRole
 * NMUserRole description: 
 *
 * @author 
 * @version 1.0
 */
class NMUserRoleBase extends Node
{
    function __construct($oid=null, $type=null)
    {
      if ($type == null)
        parent::__construct('NMUserRole', $oid);
      else
        parent::__construct($type, $oid);
    }
    /**
     * @see PersistentObject::getObjectDisplayName()
     */
    function getObjectDisplayName()
    {
      return Message::get("NMUserRole");
    }
    /**
     * @see PersistentObject::getObjectDescription()
     */
    function getObjectDescription()
    {
      return Message::get("");
    }
    /**
     * @see PersistentObject::getValueDisplayName()
     */
    function getValueDisplayName($name, $type=null)
    {
      $displayName = $name;
      if ($name == 'fk_user_id') $displayName = Message::get("fk_user_id");
      if ($name == 'fk_role_id') $displayName = Message::get("fk_role_id");
      return Message::get($displayName);
    }
    /**
     * @see PersistentObject::getValueDescription()
     */
    function getValueDescription($name, $type=null)
    {
      $description = $name;
      if ($name == 'fk_user_id') $description = Message::get("");
      if ($name == 'fk_role_id') $description = Message::get("");
      return Message::get($description);
    }
    /**
     * Getter/Setter for properties
     */
    function getFkUserId($unconverted=false)
    {
      if ($unconverted) {
        return $this->getUnconvertedValue('fk_user_id');
      }
      else {
        return $this->getValue('fk_user_id');
      }
    }
    function setFkUserId($fk_user_id)
    {
      return $this->setValue('fk_user_id', $fk_user_id);
    }
    function getFkRoleId($unconverted=false)
    {
      if ($unconverted) {
        return $this->getUnconvertedValue('fk_role_id');
      }
      else {
        return $this->getValue('fk_role_id');
      }
    }
    function setFkRoleId($fk_role_id)
    {
      return $this->setValue('fk_role_id', $fk_role_id);
    }
    /**
     * Related node lists
     */
    function getRoleRDBList()
    {
      return $this->getParentsEx(null, 'RoleRDB');
    }
    function setRoleRDBList(array $nodeList)
    {
      $this->setValue('RoleRDB', null);
      foreach ($nodeList as $node) {
        $this->addNode($node, 'RoleRDB');
      }
    }
    function getUserRDBList()
    {
      return $this->getParentsEx(null, 'UserRDB');
    }
    function setUserRDBList(array $nodeList)
    {
      $this->setValue('UserRDB', null);
      foreach ($nodeList as $node) {
        $this->addNode($node, 'UserRDB');
      }
    }
}
?>
