<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from newroles.uml on Tue May 17 15:35:25 CEST 2011. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(WCMF_BASE."application/include/model/wcmf/class.LanguageBase.php");
// PROTECTED REGION ID(application/include/model/wcmf/class.Language.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class Language
 * Language description: A llanguage for which a translation of the model can be created. The code is arbitrary but it is recommended to use the ISO language codes (en, de, it, ...).
 *
 * @author 
 * @version 1.0
 */
class Language extends LanguageBase
{
// PROTECTED REGION ID(application/include/model/wcmf/class.Language.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
