<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from newroles.uml on Thu May 26 15:54:56 CEST 2011. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(WCMF_BASE."application/include/model/wcmf/class.UserRDBBase.php");
// PROTECTED REGION ID(application/include/model/wcmf/class.UserRDB.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class UserRDB
 * UserRDB description: 
 *
 * @author 
 * @version 1.0
 */
class UserRDB extends UserRDBBase
{
// PROTECTED REGION ID(application/include/model/wcmf/class.UserRDB.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
