<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from newroles.uml on Wed Dec 15 04:52:37 CET 2010. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(WCMF_BASE."wcmf/lib/model/mapper/class.NodeUnifiedRDBMapper.php");
require_once(WCMF_BASE."application/include/model/wcmf/class.Adodbseq.php");

/**
 * @class AdodbseqRDBMapper
 * AdodbseqRDBMapper maps Adodbseq Nodes to the database.
 * Adodbseq description: 
 *
 * @author 
 * @version 1.0
 */
class AdodbseqRDBMapper extends NodeUnifiedRDBMapper
{
  /**
   * @see RDBMapper::getType()
   */
  public function getType()
  {
    return 'Adodbseq';
  }
  /**
   * @see PersistenceMapper::getPkNames()
   */
  public function getPkNames()
  {
    return array('id');
  }
  /**
   * @see PersistenceMapper::getProperties()
   */
  public function getProperties()
  {
  	return array(
      'is_searchable' => true,
// PROTECTED REGION ID(application/include/model/wcmf/class.AdodbseqRDBMapper.php/Properties) ENABLED START
// PROTECTED REGION END
	);
  }
  /**
   * @see PersistenceMapper::getDefaultOrder()
   */
  public function getDefaultOrder($roleName=null)
  {
    return array();
  }
  /**
   * @see RDBMapper::getRelationDescriptions()
   */
  protected function getRelationDescriptions()
  {
    return array(
    );
  }
  /**
   * @see RDBMapper::getAttributeDescriptions()
   */
  protected function getAttributeDescriptions()
  {
    return array(
     /**
      * Value description: 
      */
      'id' => new RDBAttributeDescription('id', '', array('DATATYPE_IGNORE'), null, '', '', '', false, 'text', 'text', 'adodbseq', 'id'),
    );
  }
  /**
   * @see RDBMapper::createObject()
   */
  protected function createObject(ObjectId $oid=null)
  {
    return new Adodbseq($oid);
  }
  /**
   * @see NodeUnifiedRDBMapper::getTableName()
   */
  protected function getTableName()
  {
    return 'adodbseq';
  }
}
?>
