<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from newroles.uml on Tue Aug 24 08:05:29 CEST 2010. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(WCMF_BASE."application/include/model/wcmf/class.RoleRDBBase.php");
// PROTECTED REGION ID(application/include/model/wcmf/class.RoleRDB.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class RoleRDB
 * RoleRDB description: 
 *
 * @author 
 * @version 1.0
 */
class RoleRDB extends RoleRDBBase
{
// PROTECTED REGION ID(application/include/model/wcmf/class.RoleRDB.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
