<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from newroles.uml on Tue May 17 15:35:25 CEST 2011.
 * Manual modifications should be placed inside the protected regions.
 */
require_once(WCMF_BASE."wcmf/lib/model/class.Node.php");

/**
 * @class EntityBase
 * EntityBase description: 
 *
 * @author 
 * @version 1.0
 */
class EntityBaseBase extends Node
{
    function __construct($oid=null, $type=null)
    {
      if ($type == null)
        parent::__construct('EntityBase', $oid);
      else
        parent::__construct($type, $oid);
    }
    /**
     * @see PersistentObject::getObjectDisplayName()
     */
    function getObjectDisplayName()
    {
      return Message::get("EntityBase");
    }
    /**
     * @see PersistentObject::getObjectDescription()
     */
    function getObjectDescription()
    {
      return Message::get("");
    }
    /**
     * @see PersistentObject::getValueDisplayName()
     */
    function getValueDisplayName($name, $type=null)
    {
      $displayName = $name;
      if ($name == 'id') $displayName = Message::get("id");
      if ($name == 'created') $displayName = Message::get("created");
      if ($name == 'creator') $displayName = Message::get("creator");
      if ($name == 'modified') $displayName = Message::get("modified");
      if ($name == 'last_editor') $displayName = Message::get("last_editor");
      return Message::get($displayName);
    }
    /**
     * @see PersistentObject::getValueDescription()
     */
    function getValueDescription($name, $type=null)
    {
      $description = $name;
      if ($name == 'id') $description = Message::get("");
      if ($name == 'created') $description = Message::get("");
      if ($name == 'creator') $description = Message::get("");
      if ($name == 'modified') $description = Message::get("");
      if ($name == 'last_editor') $description = Message::get("");
      return Message::get($description);
    }
    /**
     * Getter/Setter for properties
     */
    function getId($unconverted=false)
    {
      if ($unconverted) {
        return $this->getUnconvertedValue('id');
      }
      else {
        return $this->getValue('id');
      }
    }
    function setId($id)
    {
      return $this->setValue('id', $id);
    }
    function getCreated($unconverted=false)
    {
      if ($unconverted) {
        return $this->getUnconvertedValue('created');
      }
      else {
        return $this->getValue('created');
      }
    }
    function setCreated($created)
    {
      return $this->setValue('created', $created);
    }
    function getCreator($unconverted=false)
    {
      if ($unconverted) {
        return $this->getUnconvertedValue('creator');
      }
      else {
        return $this->getValue('creator');
      }
    }
    function setCreator($creator)
    {
      return $this->setValue('creator', $creator);
    }
    function getModified($unconverted=false)
    {
      if ($unconverted) {
        return $this->getUnconvertedValue('modified');
      }
      else {
        return $this->getValue('modified');
      }
    }
    function setModified($modified)
    {
      return $this->setValue('modified', $modified);
    }
    function getLastEditor($unconverted=false)
    {
      if ($unconverted) {
        return $this->getUnconvertedValue('last_editor');
      }
      else {
        return $this->getValue('last_editor');
      }
    }
    function setLastEditor($last_editor)
    {
      return $this->setValue('last_editor', $last_editor);
    }
}
?>
