<?php
/**
 * This file was generated by ChronosGenerator  from cwm-export.uml on Tue Feb 19 19:45:31 CET 2013. 
 * Manual modifications should be placed inside the protected regions.
 * NOTE: This file was created in the application root directory to 
 *       ensure that everything is working correctly
 */
require_once("base_dir.php");  
require_once(WCMF_BASE."wcmf/lib/presentation/Application.php");
require_once(WCMF_BASE."wcmf/lib/security/AuthUser.php");
require_once(WCMF_BASE."wcmf/3rdparty/nusoap/lib/nusoap.php");
require_once(WCMF_BASE."wcmf/lib/util/Log.php");
require_once(WCMF_BASE."wcmf/lib/presentation/ActionMapper.php");
require_once(WCMF_BASE."wcmf/lib/presentation/Request.php");
// PROTECTED REGION ID(/soap/Import) ENABLED START
// PROTECTED REGION END

$NAMESPACE = 'http://wcmf.sourceforge.net';
$server = new soap_server();
$server->configureWSDL('SOAPService', $NAMESPACE);
$server->wsdl->schemaTargetNamespace = $NAMESPACE;

$server->wsdl->addComplexType(
    'OidList',
    'complexType',
    'array',
    '',
    'SOAP-ENC:Array',
    array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'xsd:string[]')
    ),
    'xsd:string'
);
$server->wsdl->addComplexType(
    'ObjectList',
    'complexType',
    'array',
    '',
    'SOAP-ENC:Array',
    array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:object[]')
    ),
    'tns:object'
);
$server->wsdl->addComplexType('object', 'complexType', 'struct', 'sequence', '',
    array(
        'type' => array('name' => 'type', 'type' => 'xsd:string'),
        'oid' => array('name' => 'oid', 'type' => 'xsd:string'),
        'displayName' => array('name' => 'displayName', 'type' => 'xsd:string')
    )
);

/**
 * WSDL definition for Author
 */
$server->wsdl->addComplexType('Author', 'complexType', 'struct', 'sequence', '',
    array(
        'id' => array('name' => 'id', 'type' => 'xsd:string'),
        'name' => array('name' => 'name', 'type' => 'xsd:string'),
        'created' => array('name' => 'created', 'type' => 'xsd:string'),
        'creator' => array('name' => 'creator', 'type' => 'xsd:string'),
        'modified' => array('name' => 'modified', 'type' => 'xsd:string'),
        'last_editor' => array('name' => 'last_editor', 'type' => 'xsd:string'),
        'Page' => array('name' => 'Page', 'type' => 'tns:PageList'),
        'parentoids' => array('name' => 'parentoids', 'type' => 'tns:OidList'),
        'childoids' => array('name' => 'childoids', 'type' => 'tns:OidList')
    )
);
$server->wsdl->addComplexType('AuthorList', 'complexType', 'array', '', 'SOAP-ENC:Array', array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:Author[]')
    ),
    'tns:Author'
);
$server->register('getAuthorList',
  array('login'=>'xsd:string', 'password'=>'xsd:string'),
  array('return'=>'tns:AuthorList'), $NAMESPACE);
  
$server->register('createAuthor',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'Author'=>'tns:Author', 'parentoid'=>'xsd:string'),
  array('return'=>'xsd:string'), $NAMESPACE);
  
$server->register('readAuthor',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'oid'=>'xsd:string', 'depth'=>'xsd:integer'),
  array('return'=>'tns:Author'), $NAMESPACE);
  
$server->register('updateAuthor',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'Author'=>'tns:Author', 'oid'=>'xsd:string'),
  array('return'=>'xsd:string'), $NAMESPACE);
  
$server->register('deleteAuthor',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'oid'=>'xsd:string'),
  array('return'=>'xsd:string'), $NAMESPACE);

/**
 * WSDL definition for Document
 */
$server->wsdl->addComplexType('Document', 'complexType', 'struct', 'sequence', '',
    array(
        'id' => array('name' => 'id', 'type' => 'xsd:string'),
        'title' => array('name' => 'title', 'type' => 'xsd:string'),
        'created' => array('name' => 'created', 'type' => 'xsd:string'),
        'creator' => array('name' => 'creator', 'type' => 'xsd:string'),
        'modified' => array('name' => 'modified', 'type' => 'xsd:string'),
        'last_editor' => array('name' => 'last_editor', 'type' => 'xsd:string'),
        'NMPageDocument' => array('name' => 'NMPageDocument', 'type' => 'tns:NMPageDocumentList'),
        'parentoids' => array('name' => 'parentoids', 'type' => 'tns:OidList'),
        'childoids' => array('name' => 'childoids', 'type' => 'tns:OidList')
    )
);
$server->wsdl->addComplexType('DocumentList', 'complexType', 'array', '', 'SOAP-ENC:Array', array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:Document[]')
    ),
    'tns:Document'
);
$server->register('getDocumentList',
  array('login'=>'xsd:string', 'password'=>'xsd:string'),
  array('return'=>'tns:DocumentList'), $NAMESPACE);
  
$server->register('createDocument',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'Document'=>'tns:Document', 'parentoid'=>'xsd:string'),
  array('return'=>'xsd:string'), $NAMESPACE);
  
$server->register('readDocument',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'oid'=>'xsd:string', 'depth'=>'xsd:integer'),
  array('return'=>'tns:Document'), $NAMESPACE);
  
$server->register('updateDocument',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'Document'=>'tns:Document', 'oid'=>'xsd:string'),
  array('return'=>'xsd:string'), $NAMESPACE);
  
$server->register('deleteDocument',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'oid'=>'xsd:string'),
  array('return'=>'xsd:string'), $NAMESPACE);

/**
 * WSDL definition for EntityBase
 */
$server->wsdl->addComplexType('EntityBase', 'complexType', 'struct', 'sequence', '',
    array(
        'id' => array('name' => 'id', 'type' => 'xsd:string'),
        'created' => array('name' => 'created', 'type' => 'xsd:string'),
        'creator' => array('name' => 'creator', 'type' => 'xsd:string'),
        'modified' => array('name' => 'modified', 'type' => 'xsd:string'),
        'last_editor' => array('name' => 'last_editor', 'type' => 'xsd:string'),
        'parentoids' => array('name' => 'parentoids', 'type' => 'tns:OidList'),
        'childoids' => array('name' => 'childoids', 'type' => 'tns:OidList')
    )
);
$server->wsdl->addComplexType('EntityBaseList', 'complexType', 'array', '', 'SOAP-ENC:Array', array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:EntityBase[]')
    ),
    'tns:EntityBase'
);

/**
 * WSDL definition for Image
 */
$server->wsdl->addComplexType('Image', 'complexType', 'struct', 'sequence', '',
    array(
        'id' => array('name' => 'id', 'type' => 'xsd:string'),
        'fk_page_id' => array('name' => 'fk_page_id', 'type' => 'xsd:string'),
        'fk_titlepage_id' => array('name' => 'fk_titlepage_id', 'type' => 'xsd:string'),
        'filename' => array('name' => 'filename', 'type' => 'xsd:string'),
        'created' => array('name' => 'created', 'type' => 'xsd:string'),
        'creator' => array('name' => 'creator', 'type' => 'xsd:string'),
        'modified' => array('name' => 'modified', 'type' => 'xsd:string'),
        'last_editor' => array('name' => 'last_editor', 'type' => 'xsd:string'),
        'sortkey' => array('name' => 'sortkey', 'type' => 'xsd:string'),
        'parentoids' => array('name' => 'parentoids', 'type' => 'tns:OidList'),
        'childoids' => array('name' => 'childoids', 'type' => 'tns:OidList')
    )
);
$server->wsdl->addComplexType('ImageList', 'complexType', 'array', '', 'SOAP-ENC:Array', array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:Image[]')
    ),
    'tns:Image'
);
$server->register('getImageList',
  array('login'=>'xsd:string', 'password'=>'xsd:string'),
  array('return'=>'tns:ImageList'), $NAMESPACE);
  
$server->register('createImage',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'Image'=>'tns:Image', 'parentoid'=>'xsd:string'),
  array('return'=>'xsd:string'), $NAMESPACE);
  
$server->register('readImage',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'oid'=>'xsd:string', 'depth'=>'xsd:integer'),
  array('return'=>'tns:Image'), $NAMESPACE);
  
$server->register('updateImage',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'Image'=>'tns:Image', 'oid'=>'xsd:string'),
  array('return'=>'xsd:string'), $NAMESPACE);
  
$server->register('deleteImage',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'oid'=>'xsd:string'),
  array('return'=>'xsd:string'), $NAMESPACE);

/**
 * WSDL definition for Page
 */
$server->wsdl->addComplexType('Page', 'complexType', 'struct', 'sequence', '',
    array(
        'id' => array('name' => 'id', 'type' => 'xsd:string'),
        'fk_page_id' => array('name' => 'fk_page_id', 'type' => 'xsd:string'),
        'fk_author_id' => array('name' => 'fk_author_id', 'type' => 'xsd:string'),
        'name' => array('name' => 'name', 'type' => 'xsd:string'),
        'created' => array('name' => 'created', 'type' => 'xsd:string'),
        'creator' => array('name' => 'creator', 'type' => 'xsd:string'),
        'modified' => array('name' => 'modified', 'type' => 'xsd:string'),
        'last_editor' => array('name' => 'last_editor', 'type' => 'xsd:string'),
        'sortkey' => array('name' => 'sortkey', 'type' => 'xsd:string'),
        'Image' => array('name' => 'Image', 'type' => 'tns:ImageList'),
        'Image' => array('name' => 'Image', 'type' => 'tns:ImageList'),
        'Page' => array('name' => 'Page', 'type' => 'tns:PageList'),
        'NMPageDocument' => array('name' => 'NMPageDocument', 'type' => 'tns:NMPageDocumentList'),
        'parentoids' => array('name' => 'parentoids', 'type' => 'tns:OidList'),
        'childoids' => array('name' => 'childoids', 'type' => 'tns:OidList')
    )
);
$server->wsdl->addComplexType('PageList', 'complexType', 'array', '', 'SOAP-ENC:Array', array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:Page[]')
    ),
    'tns:Page'
);
$server->register('getPageList',
  array('login'=>'xsd:string', 'password'=>'xsd:string'),
  array('return'=>'tns:PageList'), $NAMESPACE);
  
$server->register('createPage',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'Page'=>'tns:Page', 'parentoid'=>'xsd:string'),
  array('return'=>'xsd:string'), $NAMESPACE);
  
$server->register('readPage',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'oid'=>'xsd:string', 'depth'=>'xsd:integer'),
  array('return'=>'tns:Page'), $NAMESPACE);
  
$server->register('updatePage',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'Page'=>'tns:Page', 'oid'=>'xsd:string'),
  array('return'=>'xsd:string'), $NAMESPACE);
  
$server->register('deletePage',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'oid'=>'xsd:string'),
  array('return'=>'xsd:string'), $NAMESPACE);

/**
 * WSDL definition for NMPageDocument
 */
$server->wsdl->addComplexType('NMPageDocument', 'complexType', 'struct', 'sequence', '',
    array(
        'id' => array('name' => 'id', 'type' => 'xsd:string'),
        'fk_page_id' => array('name' => 'fk_page_id', 'type' => 'xsd:string'),
        'fk_document_id' => array('name' => 'fk_document_id', 'type' => 'xsd:string'),
        'parentoids' => array('name' => 'parentoids', 'type' => 'tns:OidList'),
        'childoids' => array('name' => 'childoids', 'type' => 'tns:OidList')
    )
);
$server->wsdl->addComplexType('NMPageDocumentList', 'complexType', 'array', '', 'SOAP-ENC:Array', array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:NMPageDocument[]')
    ),
    'tns:NMPageDocument'
);

/**
 * WSDL definition for Adodbseq
 */
$server->wsdl->addComplexType('Adodbseq', 'complexType', 'struct', 'sequence', '',
    array(
        'id' => array('name' => 'id', 'type' => 'xsd:string'),
        'parentoids' => array('name' => 'parentoids', 'type' => 'tns:OidList'),
        'childoids' => array('name' => 'childoids', 'type' => 'tns:OidList')
    )
);
$server->wsdl->addComplexType('AdodbseqList', 'complexType', 'array', '', 'SOAP-ENC:Array', array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:Adodbseq[]')
    ),
    'tns:Adodbseq'
);

/**
 * WSDL definition for Language
 */
$server->wsdl->addComplexType('Language', 'complexType', 'struct', 'sequence', '',
    array(
        'id' => array('name' => 'id', 'type' => 'xsd:string'),
        'name' => array('name' => 'name', 'type' => 'xsd:string'),
        'code' => array('name' => 'code', 'type' => 'xsd:string'),
        'parentoids' => array('name' => 'parentoids', 'type' => 'tns:OidList'),
        'childoids' => array('name' => 'childoids', 'type' => 'tns:OidList')
    )
);
$server->wsdl->addComplexType('LanguageList', 'complexType', 'array', '', 'SOAP-ENC:Array', array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:Language[]')
    ),
    'tns:Language'
);

/**
 * WSDL definition for Locktable
 */
$server->wsdl->addComplexType('Locktable', 'complexType', 'struct', 'sequence', '',
    array(
        'id' => array('name' => 'id', 'type' => 'xsd:string'),
        'fk_user_id' => array('name' => 'fk_user_id', 'type' => 'xsd:string'),
        'objectid' => array('name' => 'objectid', 'type' => 'xsd:string'),
        'sessionid' => array('name' => 'sessionid', 'type' => 'xsd:string'),
        'since' => array('name' => 'since', 'type' => 'xsd:string'),
        'parentoids' => array('name' => 'parentoids', 'type' => 'tns:OidList'),
        'childoids' => array('name' => 'childoids', 'type' => 'tns:OidList')
    )
);
$server->wsdl->addComplexType('LocktableList', 'complexType', 'array', '', 'SOAP-ENC:Array', array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:Locktable[]')
    ),
    'tns:Locktable'
);

/**
 * WSDL definition for RoleRDB
 */
$server->wsdl->addComplexType('RoleRDB', 'complexType', 'struct', 'sequence', '',
    array(
        'id' => array('name' => 'id', 'type' => 'xsd:string'),
        'name' => array('name' => 'name', 'type' => 'xsd:string'),
        'NMUserRole' => array('name' => 'NMUserRole', 'type' => 'tns:NMUserRoleList'),
        'parentoids' => array('name' => 'parentoids', 'type' => 'tns:OidList'),
        'childoids' => array('name' => 'childoids', 'type' => 'tns:OidList')
    )
);
$server->wsdl->addComplexType('RoleRDBList', 'complexType', 'array', '', 'SOAP-ENC:Array', array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:RoleRDB[]')
    ),
    'tns:RoleRDB'
);

/**
 * WSDL definition for Translation
 */
$server->wsdl->addComplexType('Translation', 'complexType', 'struct', 'sequence', '',
    array(
        'id' => array('name' => 'id', 'type' => 'xsd:string'),
        'objectid' => array('name' => 'objectid', 'type' => 'xsd:string'),
        'attribute' => array('name' => 'attribute', 'type' => 'xsd:string'),
        'translation' => array('name' => 'translation', 'type' => 'xsd:string'),
        'language' => array('name' => 'language', 'type' => 'xsd:string'),
        'parentoids' => array('name' => 'parentoids', 'type' => 'tns:OidList'),
        'childoids' => array('name' => 'childoids', 'type' => 'tns:OidList')
    )
);
$server->wsdl->addComplexType('TranslationList', 'complexType', 'array', '', 'SOAP-ENC:Array', array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:Translation[]')
    ),
    'tns:Translation'
);

/**
 * WSDL definition for UserConfig
 */
$server->wsdl->addComplexType('UserConfig', 'complexType', 'struct', 'sequence', '',
    array(
        'id' => array('name' => 'id', 'type' => 'xsd:string'),
        'fk_user_id' => array('name' => 'fk_user_id', 'type' => 'xsd:string'),
        'key' => array('name' => 'key', 'type' => 'xsd:string'),
        'val' => array('name' => 'val', 'type' => 'xsd:string'),
        'parentoids' => array('name' => 'parentoids', 'type' => 'tns:OidList'),
        'childoids' => array('name' => 'childoids', 'type' => 'tns:OidList')
    )
);
$server->wsdl->addComplexType('UserConfigList', 'complexType', 'array', '', 'SOAP-ENC:Array', array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:UserConfig[]')
    ),
    'tns:UserConfig'
);

/**
 * WSDL definition for UserRDB
 */
$server->wsdl->addComplexType('UserRDB', 'complexType', 'struct', 'sequence', '',
    array(
        'id' => array('name' => 'id', 'type' => 'xsd:string'),
        'login' => array('name' => 'login', 'type' => 'xsd:string'),
        'password' => array('name' => 'password', 'type' => 'xsd:string'),
        'name' => array('name' => 'name', 'type' => 'xsd:string'),
        'firstname' => array('name' => 'firstname', 'type' => 'xsd:string'),
        'config' => array('name' => 'config', 'type' => 'xsd:string'),
        'Locktable' => array('name' => 'Locktable', 'type' => 'tns:LocktableList'),
        'UserConfig' => array('name' => 'UserConfig', 'type' => 'tns:UserConfigList'),
        'NMUserRole' => array('name' => 'NMUserRole', 'type' => 'tns:NMUserRoleList'),
        'parentoids' => array('name' => 'parentoids', 'type' => 'tns:OidList'),
        'childoids' => array('name' => 'childoids', 'type' => 'tns:OidList')
    )
);
$server->wsdl->addComplexType('UserRDBList', 'complexType', 'array', '', 'SOAP-ENC:Array', array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:UserRDB[]')
    ),
    'tns:UserRDB'
);

/**
 * WSDL definition for NMUserRole
 */
$server->wsdl->addComplexType('NMUserRole', 'complexType', 'struct', 'sequence', '',
    array(
        'fk_user_id' => array('name' => 'fk_user_id', 'type' => 'xsd:string'),
        'fk_role_id' => array('name' => 'fk_role_id', 'type' => 'xsd:string'),
        'parentoids' => array('name' => 'parentoids', 'type' => 'tns:OidList'),
        'childoids' => array('name' => 'childoids', 'type' => 'tns:OidList')
    )
);
$server->wsdl->addComplexType('NMUserRoleList', 'complexType', 'array', '', 'SOAP-ENC:Array', array(),
    array(
        array('ref'=>'SOAP-ENC:arrayType','wsdl:arrayType'=>'tns:NMUserRole[]')
    ),
    'tns:NMUserRole'
);

$server->register('search',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'searchterm'=>'xsd:string'),
  array('return'=>'tns:ObjectList'), $NAMESPACE);

/**  
 * SOAP Method search 
 * @param login The login name
 * @param password The login password
 * @param searchterm The search term
 * @return string
 */  
function search($login, $password, $searchterm)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'searchterm' => $searchterm, 'usr_action' => 'soapSearch'));
  $result = doSoapCall();
  return $result->getValue('soapResult');
}  


$server->register('advancedSearch',
  array('login'=>'xsd:string', 'password'=>'xsd:string', 'type'=>'xsd:string', 'query'=>'xsd:string'),
  array('return'=>'tns:ObjectList'), $NAMESPACE);

/**  
 * SOAP Method advancedSearch 
 * @param login The login name
 * @param password The login password
 * @param type The type to search for
 * @param query The query definition (@see StringQuery)
 * @return string
 */  
function advancedSearch($login, $password, $type, $query)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'type' => $type, 'query' => $query, 'usr_action' => 'soapAdvancedSearch'));
  $result = doSoapCall();
  return $result->getValue('soapResult');
}  


// Use the request to (try to) invoke the service
$HTTP_RAW_POST_DATA = isset($HTTP_RAW_POST_DATA) ? $HTTP_RAW_POST_DATA : '';
$server->service($HTTP_RAW_POST_DATA);


/**  
 * SOAP Method getAuthorList 
 * @param login The login name
 * @param password The login password
 * @return string
 */  
function getAuthorList($login, $password)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'list', 'type' => 'Author'));
// PROTECTED REGION ID(soap/Methods/getAuthorList) ENABLED START
  $result = doSoapCall();
  return $result->getValue('objects');
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method createAuthor
 * @param login The login name
 * @param password The login password
 * @param Author The serialized object data
 * @param parentoid The object id of the object to add the new object as child to
 * @return string
 */  
function createAuthor($login, $password, $Author, $parentoid)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'new', 'newtype' => 'Author',  PersistenceFacade::composeOID(array('type' => 'Author')) => $Author, 'poid' => $parentoid));
// PROTECTED REGION ID(soap/Methods/createAuthor) ENABLED START
  $result = doSoapCall();
  return $result->getValue('oid');
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method readAuthor 
 * @param login The login name
 * @param password The login password
 * @param oid The object id of the object to load
 * @param depth The number of generations to load
 * @return string
 */  
function readAuthor($login, $password, $oid, $depth)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'display', 'oid' => $oid, 'depth' => $depth));
// PROTECTED REGION ID(soap/Methods/readAuthor) ENABLED START
  $result = doSoapCall();
  return $result->getValue('node');
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method updateAuthor 
 * @param login The login name
 * @param password The login password
 * @param Author The serialized object data
 * @param oid The object id of the object to update
 * @return string
 */  
function updateAuthor($login, $password, $Author, $oid)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'save', $oid => $Author, 'oid' => $oid));
// PROTECTED REGION ID(soap/Methods/updateAuthor) ENABLED START
  $result = doSoapCall();
  return $result;
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method deleteAuthor
 * @param login The login name
 * @param password The login password
 * @param oid The object id of the object to delete
 * @return string
 */  
function deleteAuthor($login, $password, $oid)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'delete', 'deleteoids' => $oid));
// PROTECTED REGION ID(soap/Methods/deleteAuthor) ENABLED START
  $result = doSoapCall();
  return $result;
// PROTECTED REGION END
}  

/**  
 * SOAP Method getDocumentList 
 * @param login The login name
 * @param password The login password
 * @return string
 */  
function getDocumentList($login, $password)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'list', 'type' => 'Document'));
// PROTECTED REGION ID(soap/Methods/getDocumentList) ENABLED START
  $result = doSoapCall();
  return $result->getValue('objects');
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method createDocument
 * @param login The login name
 * @param password The login password
 * @param Document The serialized object data
 * @param parentoid The object id of the object to add the new object as child to
 * @return string
 */  
function createDocument($login, $password, $Document, $parentoid)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'new', 'newtype' => 'Document',  PersistenceFacade::composeOID(array('type' => 'Document')) => $Document, 'poid' => $parentoid));
// PROTECTED REGION ID(soap/Methods/createDocument) ENABLED START
  $result = doSoapCall();
  return $result->getValue('oid');
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method readDocument 
 * @param login The login name
 * @param password The login password
 * @param oid The object id of the object to load
 * @param depth The number of generations to load
 * @return string
 */  
function readDocument($login, $password, $oid, $depth)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'display', 'oid' => $oid, 'depth' => $depth));
// PROTECTED REGION ID(soap/Methods/readDocument) ENABLED START
  $result = doSoapCall();
  return $result->getValue('node');
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method updateDocument 
 * @param login The login name
 * @param password The login password
 * @param Document The serialized object data
 * @param oid The object id of the object to update
 * @return string
 */  
function updateDocument($login, $password, $Document, $oid)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'save', $oid => $Document, 'oid' => $oid));
// PROTECTED REGION ID(soap/Methods/updateDocument) ENABLED START
  $result = doSoapCall();
  return $result;
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method deleteDocument
 * @param login The login name
 * @param password The login password
 * @param oid The object id of the object to delete
 * @return string
 */  
function deleteDocument($login, $password, $oid)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'delete', 'deleteoids' => $oid));
// PROTECTED REGION ID(soap/Methods/deleteDocument) ENABLED START
  $result = doSoapCall();
  return $result;
// PROTECTED REGION END
}  

/**  
 * SOAP Method getImageList 
 * @param login The login name
 * @param password The login password
 * @return string
 */  
function getImageList($login, $password)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'list', 'type' => 'Image'));
// PROTECTED REGION ID(soap/Methods/getImageList) ENABLED START
  $result = doSoapCall();
  return $result->getValue('objects');
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method createImage
 * @param login The login name
 * @param password The login password
 * @param Image The serialized object data
 * @param parentoid The object id of the object to add the new object as child to
 * @return string
 */  
function createImage($login, $password, $Image, $parentoid)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'new', 'newtype' => 'Image',  PersistenceFacade::composeOID(array('type' => 'Image')) => $Image, 'poid' => $parentoid));
// PROTECTED REGION ID(soap/Methods/createImage) ENABLED START
  $result = doSoapCall();
  return $result->getValue('oid');
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method readImage 
 * @param login The login name
 * @param password The login password
 * @param oid The object id of the object to load
 * @param depth The number of generations to load
 * @return string
 */  
function readImage($login, $password, $oid, $depth)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'display', 'oid' => $oid, 'depth' => $depth));
// PROTECTED REGION ID(soap/Methods/readImage) ENABLED START
  $result = doSoapCall();
  return $result->getValue('node');
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method updateImage 
 * @param login The login name
 * @param password The login password
 * @param Image The serialized object data
 * @param oid The object id of the object to update
 * @return string
 */  
function updateImage($login, $password, $Image, $oid)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'save', $oid => $Image, 'oid' => $oid));
// PROTECTED REGION ID(soap/Methods/updateImage) ENABLED START
  $result = doSoapCall();
  return $result;
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method deleteImage
 * @param login The login name
 * @param password The login password
 * @param oid The object id of the object to delete
 * @return string
 */  
function deleteImage($login, $password, $oid)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'delete', 'deleteoids' => $oid));
// PROTECTED REGION ID(soap/Methods/deleteImage) ENABLED START
  $result = doSoapCall();
  return $result;
// PROTECTED REGION END
}  

/**  
 * SOAP Method getPageList 
 * @param login The login name
 * @param password The login password
 * @return string
 */  
function getPageList($login, $password)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'list', 'type' => 'Page'));
// PROTECTED REGION ID(soap/Methods/getPageList) ENABLED START
  $result = doSoapCall();
  return $result->getValue('objects');
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method createPage
 * @param login The login name
 * @param password The login password
 * @param Page The serialized object data
 * @param parentoid The object id of the object to add the new object as child to
 * @return string
 */  
function createPage($login, $password, $Page, $parentoid)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'new', 'newtype' => 'Page',  PersistenceFacade::composeOID(array('type' => 'Page')) => $Page, 'poid' => $parentoid));
// PROTECTED REGION ID(soap/Methods/createPage) ENABLED START
  $result = doSoapCall();
  return $result->getValue('oid');
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method readPage 
 * @param login The login name
 * @param password The login password
 * @param oid The object id of the object to load
 * @param depth The number of generations to load
 * @return string
 */  
function readPage($login, $password, $oid, $depth)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'display', 'oid' => $oid, 'depth' => $depth));
// PROTECTED REGION ID(soap/Methods/readPage) ENABLED START
  $result = doSoapCall();
  return $result->getValue('node');
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method updatePage 
 * @param login The login name
 * @param password The login password
 * @param Page The serialized object data
 * @param oid The object id of the object to update
 * @return string
 */  
function updatePage($login, $password, $Page, $oid)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'save', $oid => $Page, 'oid' => $oid));
// PROTECTED REGION ID(soap/Methods/updatePage) ENABLED START
  $result = doSoapCall();
  return $result;
// PROTECTED REGION END
}  
  
/**  
 * SOAP Method deletePage
 * @param login The login name
 * @param password The login password
 * @param oid The object id of the object to delete
 * @return string
 */  
function deletePage($login, $password, $oid)  
{
  $_GET = array_merge($_GET, array('login' => $login, 'password' => $password, 'action' => 'delete', 'deleteoids' => $oid));
// PROTECTED REGION ID(soap/Methods/deletePage) ENABLED START
  $result = doSoapCall();
  return $result;
// PROTECTED REGION END
}  

/**
 * Do the soap call using the ActionMapper
 * @return The Response instance from the executed Controller
 */
function doSoapCall()
{
  // initialize the application
  $application = Application::getInstance();
  $application->setErrorHandler();
  $callParams = $application->initialize('include/', 'config.ini', 'ExitController', '', $_GET['action'], MSG_FORMAT_SOAP);

  // process the requested action
  $request = new Request(
    $callParams['controller'], 
    $callParams['context'], 
    $callParams['action'], 
    $callParams['data']
  );
  
  // login with the data given in the request
  $session = &SessionData::getInstance();
  $objectFactory = &ObjectFactory::getInstance();
  $authUser = new AuthUser();
  if ($authUser->login($request->getValue('login'), $request->getValue('password')))
  {
    // login succeeded, store the user in the session
    $session->set('auth_user', $authUser);
  
    $request->setFormat(MSG_FORMAT_SOAP);
    $request->setResponseFormat(MSG_FORMAT_SOAP);
    $response = ActionMapper::processAction($request);
    $error = $response->getValue('errorMessage');
    if (strlen($error) > 0) {
      throw new ApplicationException($request, $response, 
        ApplicationError::get('GENERAL_ERROR', array('message' => $error)));
    }
  }
  else {
    throw new ApplicationException($request, null, 
      ApplicationError::get('AUTHENTICATION_FAILED'));
  }
  // cleanup
  $lockManager = LockManager::getInstance();
  $lockManager->releaseAllLocks();
  $session->destroy();
      
  return $response;
}

/**
 * Global error handling function.
 * @param message The error message
 * @param file The php file in which the error occured (optional)
 * @param line The line in the php file in which the error occured (optional)
 * @return The value
 */
function onError($message, $file='', $line='') 
{ 
  global $server;
  $server->fault('SOAP-ENV:SERVER', $message, '', Log::getStackTrace());
  Log::error($message." (".$file.", ".$line.").\n".Log::getStackTrace());
}
?>
