<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from newroles.uml on Fri Jun 10 17:44:16 CEST 2011. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(WCMF_BASE."application/include/model/wcmf/class.AdodbseqBase.php");
// PROTECTED REGION ID(application/include/model/wcmf/class.Adodbseq.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class Adodbseq
 * Adodbseq description: 
 *
 * @author 
 * @version 1.0
 */
class Adodbseq extends AdodbseqBase
{
// PROTECTED REGION ID(application/include/model/wcmf/class.Adodbseq.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
