<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from newroles.uml on Fri Jun 10 17:44:16 CEST 2011.
 * Manual modifications should be placed inside the protected regions.
 */
namespace application\model\wcmf;

use application\model\wcmf\TranslationBase;
// PROTECTED REGION ID(application/include/model/wcmf/Translation.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class Translation
 * Translation description: Instances of this class are used to localize entity attributes. Each instance defines a translation of one attribute of one entity into one language.
 *
 * @author
 * @version 1.0
 */
class Translation extends TranslationBase
{
// PROTECTED REGION ID(application/include/model/wcmf/Translation.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
