<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from newroles.uml on Fri Jun 10 17:44:16 CEST 2011.
 * Manual modifications should be placed inside the protected regions.
 */
namespace application\model\wcmf;

use application\model\wcmf\UserConfig;
use wcmf\lib\model\mapper\NodeUnifiedRDBMapper;
use wcmf\lib\model\mapper\RDBAttributeDescription;
use wcmf\lib\model\mapper\RDBManyToOneRelationDescription;
use wcmf\lib\model\mapper\RDBMapper;
use wcmf\lib\persistence\ObjectId;

/**
 * @class UserConfigRDBMapper
 * UserConfigRDBMapper maps UserConfig Nodes to the database.
 * UserConfig description:
 *
 * @author
 * @version 1.0
 */
class UserConfigRDBMapper extends NodeUnifiedRDBMapper
{
  /**
   * @see RDBMapper::getType()
   */
  public function getType()
  {
    return 'UserConfig';
  }
  /**
   * @see PersistenceMapper::getPkNames()
   */
  public function getPkNames()
  {
    return array('id');
  }
  /**
   * @see PersistenceMapper::getProperties()
   */
  public function getProperties()
  {
    return array(
      'is_searchable' => false,
// PROTECTED REGION ID(application/include/model/wcmf/UserConfigRDBMapper.php/Properties) ENABLED START
// PROTECTED REGION END
    );
  }
  /**
   * @see RDBMapper::getOwnDefaultOrder()
   */
  public function getOwnDefaultOrder($roleName=null)
  {
    return array('sortFieldName' => 'key', 'sortDirection' => 'ASC', 'isSortkey' => false);
  }
  /**
   * @see RDBMapper::getRelationDescriptions()
   */
  protected function getRelationDescriptions()
  {
    return array(
      'UserRDB' => new RDBManyToOneRelationDescription('UserConfig', 'UserConfig', 'UserRDB', 'UserRDB', '0', 'unbounded', '1', '1', 'none', 'composite', 'true', 'true', 'parent', 'id', 'fk_user_id'),

    );
  }
  /**
   * @see RDBMapper::getAttributeDescriptions()
   */
  protected function getAttributeDescriptions()
  {
    return array(
     /**
      * Value description:
      */
      'id' => new RDBAttributeDescription('id', '', array('DATATYPE_IGNORE'), null, '', '', '', false, 'text', 'text', 'user_config', 'id'),
     /**
      * Value description:
      */
      'fk_user_id' => new RDBAttributeDescription('fk_user_id', '', array('DATATYPE_IGNORE'), null, '', '', '', false, 'text', 'text', 'user_config', 'fk_user_id'),
     /**
      * Value description:
      */
      'key' => new RDBAttributeDescription('key', 'string', array('DATATYPE_ATTRIBUTE'), null, '', '', '', false, 'text', 'text', 'user_config', 'key'),
     /**
      * Value description:
      */
      'val' => new RDBAttributeDescription('val', 'string', array('DATATYPE_ATTRIBUTE'), null, '', '', '', false, 'text', 'text', 'user_config', 'val'),
    );
  }
  /**
   * @see RDBMapper::createObject()
   */
  protected function createObject(ObjectId $oid=null)
  {
    return new UserConfig($oid);
  }
  /**
   * @see NodeUnifiedRDBMapper::getTableName()
   */
  protected function getTableName()
  {
    return 'user_config';
  }
}
?>
