<?php
/**
 * This file was generated by wCMFGenerator 2.6.1.0033 from cookbook1.xmi on 23.02.09 21:34. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/wcmf/class.AdodbseqBase.php");
// PROTECTED REGION ID(application/include/model/wcmf/class.Adodbseq.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class Adodbseq
 * Adodbseq description: 
 *
 * @author <ingo@wemove.com>
 * @version 1.0
 */
class Adodbseq extends AdodbseqBase
{
// PROTECTED REGION ID(application/include/model/wcmf/class.Adodbseq.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
