<?php
/*
 * Copyright (c) 2013 The Olympos Development Team.
 * 
 * http://sourceforge.net/projects/olympos/
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html. If redistributing this code,
 * this entire header must remain intact.
 */

/**
 * This file was generated by ChronosGenerator  from cwm-export.uml on Fri Apr 26 13:28:18 CEST 2013. 
 * Manual modifications should be placed inside the protected regions.
 */
namespace testapp\application\model\wcmf;

use testapp\application\model\wcmf\DBSequenceBase;
// PROTECTED REGION ID(testapp/application/model/wcmf/DBSequence.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class DBSequence
 * DBSequence description: ?
 *
 * @author 
 * @version 1.0
 */
class DBSequence extends DBSequenceBase {
// PROTECTED REGION ID(testapp/application/model/wcmf/DBSequence.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
