<?php
/*
 * Copyright (c) 2013 The Olympos Development Team.
 * 
 * http://sourceforge.net/projects/olympos/
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html. If redistributing this code,
 * this entire header must remain intact.
 */

/**
 * This file was generated by ChronosGenerator  from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace wcmf\test\app\src\model;

use wcmf\test\app\src\model\ImageBase;
// PROTECTED REGION ID(wcmf/test/app/src/model/Image.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class Image
 * Image description: 
 *
 * @author 
 * @version 1.0
 */
class Image extends ImageBase {
// PROTECTED REGION ID(wcmf/test/app/src/model/Image.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
