<?php
/*
 * Copyright (c) 2013 The Olympos Development Team.
 * 
 * http://sourceforge.net/projects/olympos/
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html. If redistributing this code,
 * this entire header must remain intact.
 */

/**
 * This file was generated by ChronosGenerator  from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace wcmf\test\app\src\model;

use wcmf\test\app\src\model\EntityBase;

use wcmf\lib\i18n\Message;
use wcmf\lib\persistence\ObjectId;

/**
 * @class Publisher
 * Publisher description: A publisher publishes books.
 *
 * @author 
 * @version 1.0
 */
class PublisherBase extends EntityBase {

    /**
     * Constructor
     * @param oid ObjectId instance (optional)
     */
    public function __construct($oid=null) {
      if ($oid == null) {
        $oid = new ObjectId('Publisher');
    }
      parent::__construct($oid);
    }

    /**
     * @see PersistentObject::getObjectDisplayName()
     */
    public function getObjectDisplayName() {
      return Message::get("Publisher");
    }

    /**
     * @see PersistentObject::getObjectDescription()
     */
    public function getObjectDescription() {
      return Message::get("A publisher publishes books.");
    }

    /**
     * @see PersistentObject::getValueDisplayName()
     */
    public function getValueDisplayName($name) {
      $displayName = $name;
      if (false) {}
      elseif ($name == 'id') { $displayName = Message::get("id"); }
      elseif ($name == 'name') { $displayName = Message::get("name"); }
      elseif ($name == 'created') { $displayName = Message::get("created"); }
      elseif ($name == 'creator') { $displayName = Message::get("creator"); }
      elseif ($name == 'modified') { $displayName = Message::get("modified"); }
      elseif ($name == 'last_editor') { $displayName = Message::get("last_editor"); }
      return $displayName;
    }

    /**
     * @see PersistentObject::getValueDescription()
     */
    public function getValueDescription($name) {
      $description = $name;
      if (false) {}
      elseif ($name == 'id') { $description = Message::get(""); }
      elseif ($name == 'name') { $description = Message::get(""); }
      elseif ($name == 'created') { $description = Message::get(""); }
      elseif ($name == 'creator') { $description = Message::get(""); }
      elseif ($name == 'modified') { $description = Message::get(""); }
      elseif ($name == 'last_editor') { $description = Message::get(""); }
      return $description;
    }

    /**
     * Get the Book instances in the Book relation
     * @return Array of Book instances
     */
    public function getBookList() {
      return $this->getValue('Book');
    }

    /**
     * Set the Book instances in the Book relation
     * @param nodeList Array of Book instances
     */
    public function setBookList(array $nodeList) {
      $this->setValue('Book', null);
      foreach ($nodeList as $node) {
        $this->addNode($node, 'Book');
      }
    }
    /**
     * Get the Author instances in the Author relation
     * @return Array of Author instances
     */
    public function getAuthorList() {
      return $this->getValue('Author');
    }

    /**
     * Set the Author instances in the Author relation
     * @param nodeList Array of Author instances
     */
    public function setAuthorList(array $nodeList) {
      $this->setValue('Author', null);
      foreach ($nodeList as $node) {
        $this->addNode($node, 'Author');
      }
    }
}
?>
